name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.3 
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd option-pricing-api
          git pull origin main
          cd option-pricing-api/fin-dashboard/backend
          pip install -r requirements.txt
          sudo systemctl restart optionpricingapi

