name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USERNAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            cd option-pricing-api
            git pull origin main
            cd option-pricing-api/fin-dashboard/backend
            pip install -r requirements.txt
            sudo systemctl restart optionpricingapi
            '
